### ISSUE TITLE
Hyperparameters for Training/evaluation

### ISSUE THREAD

**Issue by sarath0993** [Lydorn/Polygonization-by-Frame-Field-Learning#10]
Hello, I have opened new thread to ask details about paramters, I will close that old issue. 
My full image size is 1024x1024, In "dataset_params" you configured it as `  "data_patch_size": 725, and "input_patch_size": 512,` but the Inria dataset image resolution is 5000x5000. 
How did you give it as 725 & 512?  Is it just to reduce GPU memory allocation?

**Comment by Lydorn** [comment]
Yes, the 5000x5000 image tiles are split into 725x725 patches, on which image augmention operations are applied. And then they are cropped to 512x512 (so that the black pixels from random rotations are removed). Using 512x512 patches allows to increase the batch size (4 times compared to 1024x1024). But you can try different values, or if you have enough VRAM you can try not cropping at all.

**Comment by sarath0993** [comment]
Thank you, now I clearly understood the functions of these params. I have another question regarding "save_individual_outputs"
My config is
`save_individual_outputs": {"seg": true, "seg_mask": true, "poly_shapefile": true, "poly_viz": true, "image": false, "seg_gt": false, "seg_opencities_mask": false, "seg_luxcarta": false, "crossfield": false, "uv_angles": false, "poly_geojson": true}`

After inference done, it stores _seg_mask, seg, poly_viz, cross_field(npy) and seg_luxcarta_ but it is not storing _poly_shapefile and poly_geojson_ . in the data directory. 

my command for inference `python main.py --run_name 'inria_dataset_polygonized.unet_resnet101_pretrained.aaa' --in_filepath "./data/aaa115.png"` Any idea on how do I enable shp file and geojson saving method?
