### ISSUE TITLE
question about weighted loss

### ISSUE THREAD

**Issue by wangyi111** [Lydorn/Polygonization-by-Frame-Field-Learning#11]
Hi, i saw your paper and got something unclear: when you did the edge segmentation task, were you using dice loss + weighted cross entropy (2 classes: edge and background)? For the weighted BCE, were you using the pixel frequency of each class as the weights?

**Comment by Lydorn** [comment]
Hi wangyi111, 

There are 2 building classes in total: interior and edge. They are inclusive so that an edge pixel can also be an interior pixel. They both have their corresponding background class. For the weighted BCE, the pixel frequency of classes is indeed used for the weights. However there is more to it: the distance to the 2 closest buildings affect the weights (as in the original U-Net paper) as well as the size of the building a pixel belongs to (as in the Open Solution to the CrowdAI Challenge [https://github.com/neptune-ai/open-solution-mapping-challenge](https://github.com/neptune-ai/open-solution-mapping-challenge)). 
See the compute_seg_loss_weigths() function for the details:
[https://github.com/Lydorn/Polygonization-by-Frame-Field-Learning/blob/b551af305c1934ecf170907058741f033d123dc6/frame_field_learning/losses.py#L147](https://github.com/Lydorn/Polygonization-by-Frame-Field-Learning/blob/b551af305c1934ecf170907058741f033d123dc6/frame_field_learning/losses.py#L147)

I hope this helps!

**Comment by wangyi111** [comment]
understand now, thank you!
